version: '3.8'

services:
  node-app:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - php-app

  php-app:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "9000:9000"